"""STATUS.html – the same status as STATUS.md, as a visual page (tiles, calendar, charts, filterable log).

Called by automation/status.py at the end of main() (write(...)) – never edit STATUS.html by hand, it is
overwritten on every run. Published via GitHub Pages (workflow status.yml). One file, no external scripts;
only the IBM Plex fonts come from Google Fonts (falls back to system fonts otherwise).
"""
import csv, html, json, re
from datetime import timedelta

from status import (ACCOUNT, BRANCH, NOTES, REPO, ROOT, TYPE, WEEKDAY, clock, insights_files, issue_link,
                    local, planned, short_date, status, when)

TARGET = ROOT / "STATUS.html"
KIND_NAME = {"🤖": "Autopilot", "✅": "Approval", "📈": "Stats", "📊": "Weekly report", "🎵": "Music", "🔑": "Keys",
             "🔀": "Merge", "📡": "Radar", "💬": "Comments", "💼": "LinkedIn", "✍️": "by hand / Claude"}
SUNDAY_FIRST = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"]


# ---------- helpers ----------

def esc(text):
    return html.escape(str(text), quote=True)


def md(text):
    """Inline Markdown from STATUS.md building blocks → HTML (`code`, **bold**, [link](url))."""
    codes = []

    def keep(m):
        codes.append(f"<code>{m.group(1)}</code>")
        return f"\x00{len(codes) - 1}\x00"
    t = re.sub(r"`([^`]+)`", keep, esc(text))
    t = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", t)
    t = re.sub(r"\[([^\]]+)\]\((https?://[^)\s]+)\)", r'<a href="\2" target="_blank" rel="noopener">\1</a>', t)
    return re.sub(r"\x00(\d+)\x00", lambda m: codes[int(m.group(1))], t)


def level(s):
    """Status → display level (color always comes together with symbol + text)."""
    if s == "approved":
        return "ok"
    if s == "published":
        return "done"
    if s == "error":
        return "crit"
    if s == "cancelled":
        return "muted"
    if s == "manual":
        return "info"
    return "warn"  # draft, waiting_*


def pill(s):
    return f'<span class="pill {level(s)}">{esc(status({"status": s}))}</span>'


def point_level(p):
    if p.startswith("🔴"):
        return "crit"
    if p.startswith(("👉", "Nothing")):
        return "info"
    return "warn"


# ---------- building blocks ----------

def header(as_of, up_next):
    parts = [f'''<header class="top">
  <div>
    <div class="kicker">@maehrtax · Instagram</div>
    <h1>Status</h1>
    <p class="sub">As of: last change {esc(when(as_of))} · generated by <code>automation/status.py</code> ·
      <a href="https://github.com/{REPO}/blob/{BRANCH}/STATUS.md" target="_blank" rel="noopener">STATUS.md</a></p>
  </div>
  <nav class="jump">
    <a href="#needs">Needs you</a><a href="#progress">In progress</a><a href="#calendar">Calendar</a>
    <a href="#plan">Plan</a><a href="#numbers">Numbers</a><a href="#automation">Automation</a><a href="#log">Log</a>
  </nav>
</header>''']
    if up_next:
        t = planned(up_next)
        live = up_next["status"] in ("approved", "manual")
        note = f'<p class="hero-note">{md(up_next["note"] + issue_link(up_next))}</p>' if up_next.get("note") else ""
        parts.append(f'''<section class="hero">
  <div class="hero-left">
    <div class="kicker">{"Up next" if live else "First planned (nothing approved yet)"}</div>
    <div class="hero-title">{esc(TYPE.get(up_next["type"], up_next["type"]))} <code>{esc(up_next["id"])}</code></div>
    <div class="hero-time">{esc(when(t))} · {pill(up_next["status"])}</div>
    {note}
  </div>
  <div class="countdown" data-target="{t.isoformat()}"><span class="cd-value">–</span><span class="cd-label">until live</span></div>
</section>''')
    return "\n".join(parts)


def tiles(n, points, upcoming, workflows):
    rows = list(csv.DictReader(ACCOUNT.open())) if ACCOUNT.exists() else []
    followers, diff_text = "–", ""
    if rows:
        followers = f'{int(rows[-1]["followers_count"]):,}'
        if len(rows) > 1:
            diff = int(rows[-1]["followers_count"]) - int(rows[-2]["followers_count"])
            diff_text = f'<span class="delta {"neg" if diff < 0 else "pos" if diff > 0 else ""}">{diff:+d} since {esc(short_date(rows[-2]["date"]))}</span>'
    reach, reach_text = "–", ""
    if (files := insights_files()):
        days = sorted((json.loads(files[-1].read_text()).get("daily_reach") or {}).items())
        if days:
            reach = f"{days[-1][1]:,}"
            reach_text = f'<span class="delta">on {short_date(days[-1][0])} · 7-day avg {round(sum(v for _, v in days[-7:]) / len(days[-7:])):,}</span>'
    week = [x for x in upcoming if planned(x) <= n + timedelta(days=7)]
    open_ = [p for p in points if not p.startswith("Nothing")]
    red = sum(p.startswith("🔴") for p in open_)
    ok = sum(l.startswith("✅") for _, _, l in workflows)
    failed = sum(l.startswith("🔴") for _, _, l in workflows)
    auto_text = f"{failed} failed" if failed else ("all ok" if ok else "status only visible in Actions")
    return f'''<section class="tiles">
  <div class="tile"><div class="t-label">Followers</div><div class="t-value">{esc(followers)}</div>{diff_text}</div>
  <div class="tile"><div class="t-label">Reach (last day)</div><div class="t-value">{esc(reach)}</div>{reach_text}</div>
  <div class="tile"><div class="t-label">Planned · next 7 days</div><div class="t-value">{len(week)}</div>
    <span class="delta">{sum(x["status"] == "approved" for x in week)} approved</span></div>
  <div class="tile {"t-warn" if open_ else ""}"><div class="t-label">Needs you</div><div class="t-value">{len(open_)}</div>
    <span class="delta {"neg" if red else ""}">{f"{red} red" if red else "nothing urgent"}</span></div>
  <div class="tile {"t-crit" if failed else ""}"><div class="t-label">Automation</div><div class="t-value">{ok}/{len(workflows)}</div>
    <span class="delta {"neg" if failed else ""}">{esc(auto_text)}</span></div>
</section>'''


def needs(points):
    li = "".join(f'<li class="card {point_level(p)}">{md(p)}</li>' for p in points)
    return f'<section id="needs"><h2>👉 Needs you</h2><ul class="cards">{li}</ul></section>'


def notes():
    if not NOTES.exists() or not (text := NOTES.read_text().strip()):
        return ""
    out, in_list = [], False
    for line in text.splitlines():
        if m := re.match(r"\s*[-*] (.*)", line):
            if not in_list:
                out.append("<ul class='notes'>")
                in_list = True
            out.append(f"<li>{md(m.group(1))}</li>")
        elif line.strip():
            if in_list:
                out.append("</ul>")
                in_list = False
            out.append(f"<p>{md(line.lstrip('# '))}</p>")
    if in_list:
        out.append("</ul>")
    return f'<section id="progress"><h2>📝 In progress</h2><div class="block">{"".join(out)}</div></section>'


def calendar(n, entries):
    """Four weeks starting Sunday of this week (US calendar), every entry as a chip with time, type and status."""
    start = n.date() - timedelta(days=(n.weekday() + 1) % 7)
    days = [start + timedelta(days=i) for i in range(28)]
    by_day = {}
    for x in entries:
        if x["status"] != "cancelled":
            by_day.setdefault(planned(x).date(), []).append(x)
    cells = "".join(f'<div class="cal-head">{w}</div>' for w in SUNDAY_FIRST)
    for d in days:
        chips = "".join(
            f'<div class="chip {level(x["status"])}" title="{esc(x["id"])} · {esc(status(x))}">'
            f'<span class="chip-time">{clock(planned(x))}</span> {esc(TYPE.get(x["type"], x["type"]).split(" ")[0])} '
            f'<span class="chip-id">{esc(x["id"])}</span></div>'
            for x in sorted(by_day.get(d, []), key=planned))
        cls = "cal-day" + (" today" if d == n.date() else "") + (" past" if d < n.date() else "")
        cells += f'<div class="{cls}"><div class="cal-date">{WEEKDAY[d.weekday()]} {d.month}/{d.day}</div>{chips}</div>'
    legend = "".join(f'<span class="pill {s}">{t}</span>' for s, t in (
        ("done", "✅ published"), ("ok", "🟢 approved"), ("warn", "🟡 draft / ⏳ waiting"),
        ("info", "✋ by hand"), ("crit", "🔴 error")))
    return f'''<section id="calendar"><h2>🗓️ Calendar – 4 weeks <span class="quiet">(times ET)</span></h2>
<div class="legend">{legend}</div>
<div class="cal-scroll"><div class="cal">{cells}</div></div></section>'''


def plan_table(n, upcoming):
    week = sorted((x for x in upcoming if planned(x) <= n + timedelta(days=7)), key=planned)
    later = sorted((x for x in upcoming if planned(x) > n + timedelta(days=7)), key=planned)

    def rows(items):
        return "".join(
            f'<tr><td class="nowrap">{esc(when(planned(x)))}</td><td class="nowrap">{esc(TYPE.get(x["type"], x["type"]))}<br><code>{esc(x["id"])}</code></td>'
            f'<td>{pill(x["status"])}</td><td class="note">{md(x.get("note", "") + issue_link(x))}</td></tr>'
            for x in items) or '<tr><td colspan="4">Nothing planned.</td></tr>'
    head = "<thead><tr><th>When (ET)</th><th>What</th><th>Status</th><th>Note</th></tr></thead>"
    parts = [f'<section id="plan"><h2>⏭️ Next 7 days</h2><div class="tab-scroll"><table>{head}<tbody>{rows(week)}</tbody></table></div>']
    if later:
        parts.append(f'<h3>Later</h3><div class="tab-scroll"><table>{head}<tbody>{rows(later)}</tbody></table></div>')
    return "".join(parts) + "</section>"


def recent(entries):
    done = sorted((x for x in entries if x["status"] == "published"), key=planned, reverse=True)[:10]
    if not done:
        return ""
    li = "".join(
        f'<li><span class="nowrap">{esc(when(planned(x)))}</span> · {esc(TYPE.get(x["type"], x["type"]))} <code>{esc(x["id"])}</code>'
        + (f' · <a href="{esc(x["link"])}" target="_blank" rel="noopener">view ↗</a>' if x.get("link") else "") + "</li>"
        for x in done)
    return f'<section><h2>✅ Recently published</h2><ul class="list">{li}</ul></section>'


def bars(values, height=180):
    """Column chart (one series) as SVG; hover tooltip via data-tip."""
    if not values:
        return ""
    width, left, bottom, top_pad = 1100, 40, 22, 8
    high = max(v for _, v in values) or 1
    step = next(s for s in (1, 2, 5, 10, 20, 25, 50, 100, 200, 250, 500, 1000, 2000, 5000, 10**9) if high / s <= 4)
    top = -(-high // step) * step
    y = lambda v: top_pad + (height - top_pad - bottom) * (1 - v / top)
    slot = (width - left) / len(values)
    parts = [f'<svg class="chart" viewBox="0 0 {width} {height}" role="img" aria-label="Reach per day">']
    for t in range(0, top + 1, step):
        parts.append(f'<line class="grid" x1="{left}" x2="{width}" y1="{y(t):.1f}" y2="{y(t):.1f}"/>'
                     f'<text class="axis" x="{left - 6}" y="{y(t) + 4:.1f}" text-anchor="end">{t:,}</text>')
    b = max(2, min(18, slot - 2))
    every = max(1, len(values) // 8)
    for i, (d, v) in enumerate(values):
        x = left + i * slot + (slot - b) / 2
        h = max(0.0, (height - bottom) - y(v))
        rad = min(4, b / 2, h)
        tip = f"{short_date(d)}: {v:,} reached"
        parts.append(f'<rect class="hit" x="{left + i * slot:.1f}" y="{top_pad}" width="{slot:.1f}" height="{height - top_pad - bottom}" data-tip="{esc(tip)}"/>')
        if h > 0:
            parts.append(f'<path class="bar" d="M{x:.1f},{height - bottom} v{-(h - rad):.1f} q0,{-rad:.1f} {rad:.1f},{-rad:.1f} '
                         f'h{b - 2 * rad:.1f} q{rad:.1f},0 {rad:.1f},{rad:.1f} v{h - rad:.1f} z" pointer-events="none"/>')
        if (i % every == 0 and len(values) - 1 - i >= every / 2) or i == len(values) - 1:
            parts.append(f'<text class="axis" x="{x + b / 2:.1f}" y="{height - 6}" text-anchor="middle">{short_date(d)}</text>')
    last = values[-1]
    parts.append(f'<text class="value" x="{left + (len(values) - 0.5) * slot:.1f}" y="{y(last[1]) - 6:.1f}" text-anchor="end">{last[1]:,}</text>')
    return "".join(parts) + "</svg>"


def line(points, height=150):
    """Follower trend as a line (one series), dots ≥ 8 px, hover tooltip."""
    if len(points) < 2:
        return ""
    width, left, bottom, top_pad = 1100, 46, 22, 16
    values = [v for _, v in points]
    lo, hi = min(values), max(values)
    if hi - lo < 4:
        lo, hi = lo - 2, hi + 2
    y = lambda v: top_pad + (height - top_pad - bottom) * (1 - (v - lo) / (hi - lo))
    x = lambda i: left + 10 + (width - left - 20) * i / (len(points) - 1)
    parts = [f'<svg class="chart" viewBox="0 0 {width} {height}" role="img" aria-label="Follower trend">']
    for t in (lo, (lo + hi) / 2, hi):
        parts.append(f'<line class="grid" x1="{left}" x2="{width}" y1="{y(t):.1f}" y2="{y(t):.1f}"/>'
                     f'<text class="axis" x="{left - 6}" y="{y(t) + 4:.1f}" text-anchor="end">{round(t):,}</text>')
    path = " ".join(f"{'M' if i == 0 else 'L'}{x(i):.1f},{y(v):.1f}" for i, (_, v) in enumerate(points))
    parts.append(f'<path class="line" d="{path}"/>')
    every = max(1, len(points) // 8)
    for i, (d, v) in enumerate(points):
        parts.append(f'<circle class="dot" cx="{x(i):.1f}" cy="{y(v):.1f}" r="4.5"/>'
                     f'<circle class="hit" cx="{x(i):.1f}" cy="{y(v):.1f}" r="14" data-tip="{esc(f"{short_date(d)}: {v:,} followers")}"/>')
        if (i % every == 0 and len(points) - 1 - i >= every / 2) or i == len(points) - 1:
            parts.append(f'<text class="axis" x="{x(i):.1f}" y="{height - 6}" text-anchor="middle">{short_date(d)}</text>')
    parts.append(f'<text class="value" x="{x(len(points) - 1):.1f}" y="{y(points[-1][1]) - 10:.1f}" text-anchor="end">{points[-1][1]:,}</text>')
    return "".join(parts) + "</svg>"


def numbers(n):
    rows = list(csv.DictReader(ACCOUNT.open())) if ACCOUNT.exists() else []
    files = insights_files()
    if not rows and not files:
        return ('<section id="numbers"><h2>📈 Numbers</h2><p>No stats yet – they start after the Instagram secrets are set '
                'and the first stats run (daily around 9:00 AM ET).</p></section>')
    parts = ['<section id="numbers"><h2>📈 Numbers <span class="quiet">(daily around 9:00 AM ET)</span></h2><div class="stack">']
    if files:
        d = json.loads(files[-1].read_text())
        days = sorted((d.get("daily_reach") or {}).items())[-30:]
        parts.append(f'<figure class="block"><figcaption>Reach per day · last {len(days)} days</figcaption>{bars(days)}</figure>')
    if rows:
        parts.append(f'<figure class="block"><figcaption>Followers</figcaption>'
                     f'{line([(z["date"], int(z["followers_count"])) for z in rows][-60:])}</figure>')
    parts.append("</div>")
    if files:
        d = json.loads(files[-1].read_text())
        old = {b["id"]: b for b in json.loads(files[-2].read_text()).get("media", [])} if len(files) > 1 else {}
        new = [b for b in d.get("media", []) if b.get("timestamp") and n - local(b["timestamp"]) < timedelta(days=14)]
        if new:
            body = ""
            for b in sorted(new, key=lambda x: x["timestamp"], reverse=True):
                plus = (f' <span class="quiet">(+{b["views"] - old[b["id"]]["views"]})</span>'
                        if isinstance(old.get(b["id"], {}).get("views"), int) and isinstance(b.get("views"), int) else "")
                name = (b.get("caption") or "").split("\n")[0][:50]
                body += (f'<tr><td><span class="nowrap">{esc(when(local(b["timestamp"])))}</span><br>'
                         f'<a href="{esc(b.get("permalink", ""))}" target="_blank" rel="noopener">{esc(name)}</a></td>'
                         + "".join(f'<td class="num">{esc(b.get(k, "–"))}{plus if k == "views" else ""}</td>'
                                   for k in ("views", "reach", "likes", "comments", "saved", "shares")) + "</tr>")
            parts.append('<h3>Posts (last 14 days)</h3><div class="tab-scroll"><table><thead><tr><th>Post</th>'
                         '<th class="num">Views</th><th class="num">Reach</th><th class="num">Likes</th><th class="num">Comments</th>'
                         f'<th class="num">Saves</th><th class="num">Shares</th></tr></thead><tbody>{body}</tbody></table></div>')
        stories = sorted((s for s in d.get("active_stories") or [] if s.get("time")), key=lambda x: x["time"])
        if stories:
            body = "".join(
                f'<tr><td class="nowrap">{esc(when(local(s["time"])))}</td>'
                + "".join(f'<td class="num">{esc(s.get(k, "–"))}</td>' for k in ("views", "reach", "replies", "profile_visits", "follows"))
                + "</tr>" for s in stories)
            parts.append('<h3>Stories (last 24 h)</h3><div class="tab-scroll"><table><thead><tr><th>Story</th><th class="num">Views</th>'
                         '<th class="num">Reach</th><th class="num">Replies</th><th class="num">Profile visits</th>'
                         f'<th class="num">Follows</th></tr></thead><tbody>{body}</tbody></table></div>')
    parts.append('<p class="quiet">Raw data: <code>automation/stats/</code> · analysis: <code>strategy/06_analytics.md</code></p></section>')
    return "".join(parts)


def automation(workflows):
    cards = ""
    for name, schedule, last in workflows:
        s = "crit" if last.startswith("🔴") else "ok" if last.startswith("✅") else "muted"
        cards += f'<div class="wf {s}"><div class="wf-name">{esc(name)}</div><div class="wf-when">{esc(schedule)}</div><div class="wf-status">{md(last)}</div></div>'
    hint = ("" if any(l != "–" for _, _, l in workflows) else
            '<p class="quiet">No runs yet (or no GH_TOKEN locally) – the status is visible under Actions once the repo is live.</p>')
    return f'<section id="automation"><h2>⚙️ Automation</h2><div class="wfs">{cards}</div>{hint}</section>'


def log(n, commits):
    counts = {}
    for c in commits:
        counts[c["kind"]] = counts.get(c["kind"], 0) + 1
    filters = '<button class="filt active" data-kind="">All <span>{}</span></button>'.format(len(commits)) + "".join(
        f'<button class="filt" data-kind="{esc(a)}">{esc(a)} {esc(KIND_NAME.get(a, ""))} <span>{z}</span></button>'
        for a, z in sorted(counts.items(), key=lambda kv: -kv[1]))
    days = {}
    for c in commits:
        days.setdefault(c["time"].date(), []).append(c)
    blocks = ""
    for d, items in days.items():
        lis = ""
        for c in items:
            details = ("Plan: " + "; ".join(c["plan"])) if c["plan"] else ", ".join(f"`{x}`" for x in c["areas"])
            search = (c["message"] + " " + details).lower()
            lis += (f'<li class="lg" data-kind="{esc(c["kind"])}" data-search="{esc(search)}">'
                    f'<span class="lg-time">{clock(c["time"])}</span><span class="lg-kind" title="{esc(KIND_NAME.get(c["kind"], ""))}">{esc(c["kind"])}</span>'
                    f'<div class="lg-text"><div>{esc(c["message"])} <a class="sha" href="https://github.com/{REPO}/commit/{c["sha"]}" '
                    f'target="_blank" rel="noopener">{c["sha"][:7]}</a></div>'
                    + (f'<div class="lg-details">{md(details)}</div>' if details else "") + "</div></li>")
        is_open = " open" if (n.date() - d).days < 7 else ""
        blocks += (f'<details class="lg-day"{is_open}><summary>{WEEKDAY[d.weekday()]} {d.month}/{d.day}/{d.year} '
                   f'<span class="quiet">· {len(items)}</span></summary><ul class="lg-list">{lis}</ul></details>')
    return f'''<section id="log"><h2>📜 Log – every change</h2>
<div class="lg-tools"><input type="search" id="lg-search" placeholder="Search (e.g. Reel, Radar, 04-…)" aria-label="Search the log">
<div class="filter">{filters}</div></div>
<div id="lg">{blocks}</div><p id="lg-empty" class="quiet" hidden>Nothing found.</p></section>'''


# ---------- page ----------

CSS = """
:root{--bg:#F4F7F5;--surface:#FFFFFF;--surface2:#EAF1EC;--border:#D5E0D9;--text:#0B110E;--text2:#3D4D44;--quiet:#66766D;
--accent:#2E8F72;--accent-text:#1F6F57;--ok:#1F7A4D;--ok-bg:#E2F3E9;--warn:#8A5A00;--warn-bg:#FBF0D9;--crit:#B42318;--crit-bg:#FCE4E1;
--info:#1D5FA8;--info-bg:#E2ECF8;--done:#4C5A52;--done-bg:#E9EEEB;--grid:#E1E8E4;--bar:#2E8F72;--shadow:0 1px 2px rgba(11,17,14,.06)}
@media (prefers-color-scheme:dark){:root:not([data-theme="light"]){--bg:#0B110E;--surface:#111A15;--surface2:#153A31;--border:#22332A;
--text:#EAF1EC;--text2:#C3D1C8;--quiet:#8FA398;--accent:#53C3A2;--accent-text:#6FD3B4;--ok:#6FD3A0;--ok-bg:#15301F;--warn:#F2C36B;
--warn-bg:#33280F;--crit:#FF8A7A;--crit-bg:#3A1512;--info:#8DB9F0;--info-bg:#14243A;--done:#A9B8AF;--done-bg:#1A231E;--grid:#1E2C24;
--bar:#53C3A2;--shadow:none}}
:root[data-theme="dark"]{--bg:#0B110E;--surface:#111A15;--surface2:#153A31;--border:#22332A;--text:#EAF1EC;--text2:#C3D1C8;--quiet:#8FA398;
--accent:#53C3A2;--accent-text:#6FD3B4;--ok:#6FD3A0;--ok-bg:#15301F;--warn:#F2C36B;--warn-bg:#33280F;--crit:#FF8A7A;--crit-bg:#3A1512;
--info:#8DB9F0;--info-bg:#14243A;--done:#A9B8AF;--done-bg:#1A231E;--grid:#1E2C24;--bar:#53C3A2;--shadow:none}
*{box-sizing:border-box}
[hidden]{display:none!important}
body{margin:0;background:var(--bg);color:var(--text);font:15px/1.55 "IBM Plex Sans",system-ui,-apple-system,"Segoe UI",sans-serif}
main{max-width:1180px;margin:0 auto;padding:24px 16px 64px}
h1,h2,h3{font-family:"IBM Plex Serif",Georgia,serif;font-weight:600;margin:0}
h1{font-size:34px;letter-spacing:-.01em}
h2{font-size:21px;margin:40px 0 14px}
h3{font-size:16px;margin:24px 0 10px}
a{color:var(--accent-text)}
code{font:12.5px "IBM Plex Mono",ui-monospace,monospace;background:var(--surface2);padding:1px 5px;border-radius:4px;word-break:break-word}
.kicker{font:12px "IBM Plex Mono",monospace;letter-spacing:.08em;text-transform:uppercase;color:var(--accent-text)}
.sub,.quiet{color:var(--quiet);font-size:13px;font-weight:400}
.top{display:flex;justify-content:space-between;align-items:flex-end;gap:16px;flex-wrap:wrap}
.jump{display:flex;flex-wrap:wrap;gap:6px}
.jump a{font-size:13px;text-decoration:none;color:var(--text2);border:1px solid var(--border);border-radius:999px;padding:4px 10px;background:var(--surface)}
.jump a:hover{border-color:var(--accent)}
.hero{margin-top:20px;display:flex;justify-content:space-between;align-items:center;gap:20px;flex-wrap:wrap;padding:22px;border-radius:14px;
background:linear-gradient(135deg,var(--surface2),var(--surface));border:1px solid var(--border)}
.hero-title{font:600 24px "IBM Plex Serif",serif;margin:4px 0}
.hero-title code{font-size:18px}
.hero-time{color:var(--text2);display:flex;gap:10px;align-items:center;flex-wrap:wrap}
.hero-note{color:var(--text2);font-size:13.5px;max-width:720px;margin:10px 0 0}
.hero-left{flex:1 1 420px;min-width:0}
.countdown{text-align:center;padding:12px 20px;border-radius:12px;background:var(--surface);border:1px solid var(--border);min-width:150px}
.cd-value{display:block;font:600 30px "IBM Plex Mono",monospace;color:var(--accent-text);font-variant-numeric:tabular-nums}
.cd-label{font-size:12px;color:var(--quiet)}
.tiles{display:grid;grid-template-columns:repeat(auto-fit,minmax(170px,1fr));gap:12px;margin-top:16px}
.tile{background:var(--surface);border:1px solid var(--border);border-radius:12px;padding:14px 16px;box-shadow:var(--shadow)}
.t-label{font-size:12.5px;color:var(--quiet)}
.t-value{font:600 30px "IBM Plex Serif",serif;margin:2px 0;font-variant-numeric:tabular-nums}
.t-warn{border-color:var(--warn)}.t-crit{border-color:var(--crit)}
.delta{font-size:12.5px;color:var(--quiet)}.delta.pos{color:var(--ok)}.delta.neg{color:var(--crit)}
.cards{list-style:none;padding:0;margin:0;display:grid;gap:8px}
.card{background:var(--surface);border:1px solid var(--border);border-left:4px solid var(--quiet);border-radius:10px;padding:10px 14px}
.card.crit{border-left-color:var(--crit);background:var(--crit-bg)}.card.warn{border-left-color:var(--warn)}.card.info{border-left-color:var(--info)}
.block{background:var(--surface);border:1px solid var(--border);border-radius:12px;padding:14px 18px;margin:0}
.notes{margin:0;padding-left:18px}.notes li{margin:6px 0;color:var(--text2)}.notes strong{color:var(--text)}
.pill{display:inline-block;font-size:12px;line-height:1.3;padding:3px 9px;border-radius:999px;white-space:nowrap;border:1px solid transparent}
.pill.ok{background:var(--ok-bg);color:var(--ok)}.pill.warn{background:var(--warn-bg);color:var(--warn)}.pill.crit{background:var(--crit-bg);color:var(--crit)}
.pill.info{background:var(--info-bg);color:var(--info)}.pill.done{background:var(--done-bg);color:var(--done)}.pill.muted{background:var(--done-bg);color:var(--quiet)}
.legend{display:flex;flex-wrap:wrap;gap:6px;margin-bottom:10px}
.cal-scroll,.tab-scroll{overflow-x:auto;-webkit-overflow-scrolling:touch}
.cal{display:grid;grid-template-columns:repeat(7,minmax(120px,1fr));gap:6px;min-width:860px}
.cal-head{font:12px "IBM Plex Mono",monospace;color:var(--quiet);text-transform:uppercase;padding:0 4px}
.cal-day{background:var(--surface);border:1px solid var(--border);border-radius:10px;padding:6px;min-height:92px}
.cal-day.today{border-color:var(--accent);box-shadow:0 0 0 1px var(--accent)}
.cal-day.past{opacity:.62}
.cal-date{font-size:12px;color:var(--quiet);margin-bottom:4px}
.chip{font-size:11.5px;line-height:1.3;border-radius:6px;padding:3px 6px;margin-top:3px;border-left:3px solid var(--quiet);background:var(--surface2);overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
.chip.ok{border-left-color:var(--ok);background:var(--ok-bg)}.chip.warn{border-left-color:var(--warn);background:var(--warn-bg)}
.chip.crit{border-left-color:var(--crit);background:var(--crit-bg)}.chip.info{border-left-color:var(--info);background:var(--info-bg)}
.chip.done{border-left-color:var(--done);background:var(--done-bg)}
.chip-time{font-family:"IBM Plex Mono",monospace;color:var(--text2)}
.chip-id{color:var(--text)}
table{width:100%;border-collapse:collapse;background:var(--surface);border:1px solid var(--border);border-radius:12px;overflow:hidden;font-size:13.5px}
th,td{text-align:left;padding:9px 12px;border-bottom:1px solid var(--border);vertical-align:top}
th{font-weight:600;font-size:12.5px;color:var(--quiet);background:var(--surface2)}
tr:last-child td{border-bottom:0}
td.num,th.num{text-align:right;font-variant-numeric:tabular-nums}
td.note{color:var(--text2);min-width:260px}
.nowrap{white-space:nowrap}
.list{margin:0;padding-left:18px}.list li{margin:4px 0}
.stack{display:grid;gap:12px}
figcaption{font-size:13px;color:var(--quiet);margin-bottom:6px}
.chart{width:100%;height:auto;display:block;overflow:visible}
.chart .grid{stroke:var(--grid);stroke-width:1}
.chart .axis{fill:var(--quiet);font:11px "IBM Plex Mono",monospace}
.chart .value{fill:var(--text);font:600 12px "IBM Plex Sans",sans-serif}
.chart .bar{fill:var(--bar)}
.chart .line{fill:none;stroke:var(--bar);stroke-width:2;stroke-linejoin:round}
.chart .dot{fill:var(--bar);stroke:var(--surface);stroke-width:2}
.chart .hit{fill:transparent;cursor:default}
.chart .hit:hover{fill:var(--surface2);fill-opacity:.55}
#tip{position:fixed;pointer-events:none;background:var(--text);color:var(--bg);font-size:12.5px;padding:5px 9px;border-radius:6px;opacity:0;transition:opacity .1s;z-index:9}
.wfs{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:10px}
.wf{background:var(--surface);border:1px solid var(--border);border-left:4px solid var(--quiet);border-radius:10px;padding:10px 14px}
.wf.ok{border-left-color:var(--ok)}.wf.crit{border-left-color:var(--crit);background:var(--crit-bg)}
.wf-name{font-weight:600}.wf-when{font-size:12.5px;color:var(--quiet);margin:2px 0 6px}.wf-status{font-size:13px}
.lg-tools{display:flex;flex-direction:column;gap:10px;margin-bottom:12px}
#lg-search{font:inherit;padding:9px 12px;border-radius:10px;border:1px solid var(--border);background:var(--surface);color:var(--text);max-width:420px}
.filter{display:flex;flex-wrap:wrap;gap:6px}
.filt{font:inherit;font-size:12.5px;border:1px solid var(--border);background:var(--surface);color:var(--text2);border-radius:999px;padding:4px 10px;cursor:pointer}
.filt span{color:var(--quiet)}
.filt.active{border-color:var(--accent);background:var(--surface2);color:var(--text)}
.lg-day{background:var(--surface);border:1px solid var(--border);border-radius:12px;margin-bottom:8px}
.lg-day summary{cursor:pointer;padding:10px 14px;font-weight:600}
.lg-list{list-style:none;margin:0;padding:0 14px 10px}
.lg{display:grid;grid-template-columns:64px 26px 1fr;gap:6px;padding:7px 0;border-top:1px solid var(--border)}
.lg-time{font:12.5px "IBM Plex Mono",monospace;color:var(--quiet);padding-top:1px}
.lg-text{min-width:0;overflow-wrap:anywhere}
.lg-details{font-size:12.5px;color:var(--quiet);margin-top:2px}
.sha{font:11.5px "IBM Plex Mono",monospace;color:var(--quiet)}
footer{margin-top:48px;color:var(--quiet);font-size:12.5px}
@media (max-width:600px){h1{font-size:28px}.hero{padding:16px}.t-value{font-size:26px}}
"""

JS = """
(function(){
  var cd=document.querySelector('.countdown');
  if(cd){var target=new Date(cd.dataset.target),v=cd.querySelector('.cd-value'),l=cd.querySelector('.cd-label');
    var tick=function(){var s=Math.round((target-new Date())/1000);
      if(s<=0){v.textContent='now';l.textContent='should be live';return;}
      var d=Math.floor(s/86400),h=Math.floor(s%86400/3600),m=Math.floor(s%3600/60);
      v.textContent=d>0?d+' d '+h+' h':h>0?h+' h '+m+' min':m+' min';};
    tick();setInterval(tick,30000);}
  var tip=document.getElementById('tip');
  document.querySelectorAll('[data-tip]').forEach(function(el){
    el.addEventListener('mousemove',function(ev){tip.textContent=el.dataset.tip;tip.style.opacity=1;
      var x=Math.min(ev.clientX+12,window.innerWidth-tip.offsetWidth-8);tip.style.left=x+'px';tip.style.top=(ev.clientY-34)+'px';});
    el.addEventListener('mouseleave',function(){tip.style.opacity=0;});});
  var kind='',search=document.getElementById('lg-search');
  function apply(){var q=(search.value||'').toLowerCase().trim(),hits=0;
    document.querySelectorAll('.lg-day').forEach(function(t){var n=0;
      t.querySelectorAll('.lg').forEach(function(li){var ok=(!kind||li.dataset.kind===kind)&&(!q||li.dataset.search.indexOf(q)>=0);
        li.hidden=!ok;if(ok)n++;});
      t.hidden=n===0;if(q||kind){if(n)t.open=true;}hits+=n;});
    document.getElementById('lg-empty').hidden=hits>0;}
  search.addEventListener('input',apply);
  document.querySelectorAll('.filt').forEach(function(b){b.addEventListener('click',function(){
    document.querySelectorAll('.filt').forEach(function(x){x.classList.remove('active');});
    b.classList.add('active');kind=b.dataset.kind;apply();});});
})();
"""


def write(n, as_of, entries, upcoming, up_next, points, workflows, commits):
    body = "\n".join([
        header(as_of, up_next),
        tiles(n, points, upcoming, workflows),
        needs(points),
        notes(),
        calendar(n, entries),
        plan_table(n, upcoming),
        recent(entries),
        numbers(n),
        automation(workflows),
        log(n, commits),
    ])
    page = f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="robots" content="noindex">
<title>maehrtax Status</title>
<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@400;600&family=IBM+Plex+Sans:wght@400;600&family=IBM+Plex+Serif:wght@600&display=swap" rel="stylesheet">
<style>{CSS}</style>
</head>
<body>
<main>
{body}
<footer>Generated by <code>automation/status_html.py</code> – do not edit by hand. Notes: <code>automation/status_notes.md</code>. All times US Eastern (ET).</footer>
</main>
<div id="tip" role="tooltip"></div>
<script>{JS}</script>
</body>
</html>
"""
    TARGET.write_text(page)
    print(f"✓ {TARGET.relative_to(ROOT)} written")
